apiVersion: v1
kind: Service
metadata:
  name: api-svc      # nom du Service
spec:
  type: NodePort     # NodePort pour accéder depuis l’extérieur du cluster (pratique en local)
  selector:
    app: api         # fait le lien avec le label du Deployment
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
